### ISSUE TITLE
Question about preprocess.py

### ISSUE THREAD

**Issue by wade3han** [bshall/UniversalVocoding#11]
Hello.

In `preprocess.py` line 17,

```
wav /= np.abs(wav).max() * 0.999
```

I'm wondering why you choose to use `* 0.999`. It leads `wav` to have value which gets over 1.0. Is it bug or intended code?

Thanks.

**Comment by bshall** [comment]
Hi @wade3han,

Thanks for picking that up. It is indeed a bug, should have been:
```
wav = wav / np.abs(wav).max() * 0.999
```
I don't think it makes a difference at the end of the day because the `mu-law` quantization would probably quantize the wav to the same values but I should fix it anyway.

**Comment by ivancarapinha** [comment]
Hello @bshall,

Shouldn't we first check if `np.abs(wav).max() > 1` ? Otherwise the .wav file would amplified, wouldn't it?
