### ISSUE TITLE
Changing parameters

### ISSUE THREAD

**Issue by sbkim052** [bshall/UniversalVocoding#15]
If i want to change the parameters of the model, what are the things should I change?
I want to change sampling_rate, num_fft, num_mels, hop length, win_length.
It seems pretty much every parameter. 

 Are there other things to change other than config.json?

**Comment by bshall** [comment]
Hi @sbkim052,

Nope, just changing things in `config.json` should work. I don't think any parameters have been hardcoded. Let me know if you have any issues. Remember to rerun `preprocess.py` when you change parameters though.

**Comment by sbkim052** [comment]
Thank you @bshall.
I will try on new parameters and share the result with you :)
