### ISSUE TITLE
path to waveform directory

### ISSUE THREAD

**Issue by maximilianchen** [bshall/UniversalVocoding#2]
Hi @bshall, I wondered how to set the path to the downloaded waveform directory when preprocessing, as it not as the parameter.

**Comment by bshall** [comment]
Hi @maximilianchen, I wrote the preprocessing.py file specifically with the structure of the ZeroSpeech2019 dataset in mind. If you're looking to train on your own dataset the easiest approach would be to change the line [here](https://github.com/bshall/UniversalVocoding/blob/master/preprocess.py#L88) to point to your directory. For example, if your `.wav` files are in the directory `~/dataset/wavs/` you should be able to change the line to
```
wav_dirs = ["~/dataset/wavs/"]
```
I hope that helps.

I can also add a command line argument if that makes things simpler?

**Comment by maximilianchen** [comment]
> Hi @maximilianchen, I wrote the preprocessing.py file specifically with the structure of the ZeroSpeech2019 dataset in mind. If you're looking to train on your own dataset the easiest approach would be to change the line [here](https://github.com/bshall/UniversalVocoding/blob/master/preprocess.py#L88) to point to your directory. For example, if your `.wav` files are in the directory `~/dataset/wavs/` you should be able to change the line to
> 
> ```
> wav_dirs = ["~/dataset/wavs/"]
> ```
> 
> I hope that helps.
> 
> I can also add a command line argument if that makes things simpler?

Thanks a lot for your information, @bshall . I had missed out the line you mentioned above when I brought up the issue. Now I have managed to point to the wav path.

**Comment by bshall** [comment]
No problem. Let me know how the training goes. I haven't tested the model out on other datasets so I'd be interested to hear how it goes.
